---
abstract: 'simple exception class'
author:
  - 'n0body <n0body@thisaintnews.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Exception: 0
  Test::More: 0
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Exception::Simple
name: Exception-Simple
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  overload: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.005
